name: WZXY_HealthCheck

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  
  schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
    - cron:  '30 16 * * *' # 默认在每天 UTC 16:30 （北京时间 0:30）执行

jobs:
  USER_01:
    runs-on: ubuntu-latest
    environment: WZXY_COMMON                               
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD1}}-${{ github.run_id }}
        restore-keys: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD1}}
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        GOBOT_URL: ${{secrets.GOBOT_URL}}
        GOBOT_QQ: ${{secrets.GOBOT_QQ}}
        GOBOT_TOKEN: ${{secrets.GOBOT_TOKEN}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME1}}
        WZXY_PASSWORD: ${{secrets.PASSWORD1}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_AREACODE: ${{secrets.AREACODE}}
        WZXY_TOWNCODE: ${{secrets.TOWNCODE}}
        WZXY_CITYCODE: ${{secrets.CITYCODE}}
        WZXY_STREET: ${{secrets.STREET}}
        WZXY_ANSWERS: ${{secrets.ANSWERS}}
      run: python wzxy-healthcheck.py

  USER_02:
    runs-on: ubuntu-latest
    environment: WZXY_COMMON                               
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD2}}-${{ github.run_id }}
        restore-keys: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD2}}
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        GOBOT_URL: ${{secrets.GOBOT_URL}}
        GOBOT_QQ: ${{secrets.GOBOT_QQ}}
        GOBOT_TOKEN: ${{secrets.GOBOT_TOKEN}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME2}}
        WZXY_PASSWORD: ${{secrets.PASSWORD2}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_AREACODE: ${{secrets.AREACODE}}
        WZXY_TOWNCODE: ${{secrets.TOWNCODE}}
        WZXY_CITYCODE: ${{secrets.CITYCODE}}
        WZXY_STREET: ${{secrets.STREET}}
        WZXY_ANSWERS: ${{secrets.ANSWERS}}
      run: python wzxy-healthcheck.py

  USER_03:
    runs-on: ubuntu-latest
    environment: WZXY_COMMON                              
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD3}}-${{ github.run_id }}
        restore-keys: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD3}}
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        GOBOT_URL: ${{secrets.GOBOT_URL}}
        GOBOT_QQ: ${{secrets.GOBOT_QQ}}
        GOBOT_TOKEN: ${{secrets.GOBOT_TOKEN}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME3}}
        WZXY_PASSWORD: ${{secrets.PASSWORD3}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_AREACODE: ${{secrets.AREACODE}}
        WZXY_TOWNCODE: ${{secrets.TOWNCODE}}
        WZXY_CITYCODE: ${{secrets.CITYCODE}}
        WZXY_STREET: ${{secrets.STREET}}
        WZXY_ANSWERS: ${{secrets.ANSWERS}}
      run: python wzxy-healthcheck.py

  USER_04:
    runs-on: ubuntu-latest
    environment: WZXY_COMMON                              
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD4}}-${{ github.run_id }}
        restore-keys: ${{ secrets.CITYCODE }}-${{secrets.PASSWORD4}}
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        GOBOT_URL: ${{secrets.GOBOT_URL}}
        GOBOT_QQ: ${{secrets.GOBOT_QQ}}
        GOBOT_TOKEN: ${{secrets.GOBOT_TOKEN}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        WZXY_USERNAME: ${{secrets.USERNAME4}}
        WZXY_PASSWORD: ${{secrets.PASSWORD4}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_AREACODE: ${{secrets.AREACODE}}
        WZXY_TOWNCODE: ${{secrets.TOWNCODE}}
        WZXY_CITYCODE: ${{secrets.CITYCODE}}
        WZXY_STREET: ${{secrets.STREET}}
        WZXY_ANSWERS: ${{secrets.ANSWERS}}
      run: python wzxy-healthcheck.py
